plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.waydroidvulkan'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.waydroidvulkan'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '0.1.0'
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = false
        }
    }
}
